version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: --init-file /data/application/college_application.sql
    volumes:
      - ./college_application.sql:/data/application/college_application.sql

  api:
    depends_on:
      - mysqldb
    build: backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    image: tanchonglim/cras-angular-sc_api

  ui:
    depends_on:
      - api
    build: frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $ANGULAR_LOCAL_PORT:$ANGULAR_DOCKER_PORT
    stdin_open: true
    tty: true
    image: tanchonglim/cras-angular-sc_ui
volumes:
  db:
